### ISSUE TITLE
Update README/project name to reflect the connection between paper and libpaper

### ISSUE THREAD

**Issue by zdohnal** [rrthomas/libpaper#22]
Hi,

since ```paperconf``` was renamed to ```paper```, then there is a conflict between existing ```paper``` binary from ```paper``` package. The package has an URL to your github repository, but it is redirected to this ```libpaper``` repo. It is confusing at first.

It would be great if README cleanly stated the connection between those two projects - IIUC you've merged those projects - so one package will have to obsolete the other. Right now the repo is called libpaper, but https:/github.com/rrthomas/paper is redirected here and README mentions paper as well.

**Comment by rrthomas** [comment]
Thanks for pointing out the confusion. "paper" was the name of the project for a while (when I reimplemented the project entirely without the C library), then I reverted to "libpaper" (when I reintroduced the C library, for backwards compatibility). The redirect from https://github.com/rrthomas/paper is maintained by GitHub, I don't think there's a lot I can do about it (eventually it should go away). I have updated the `README` to point to the current URL.

I don't really want to add explanation, because the `paper` phase of the project is essentially a dead end that was never packaged by anyone as far as I know.

**Comment by zdohnal** [comment]
> I don't really want to add explanation, because the `paper` phase of the project is essentially a dead end that was never packaged by anyone as far as I know.

It was packaged at least in Fedora https://src.fedoraproject.org/rpms/paper  and Arch Linux https://archlinux.org/packages/extra/x86_64/paper/ , maybe others, so it would be great if an explanation was placed into README.

Since the ```paper``` already is in some distros, IMHO it would be easier to get the project into Debian and obsolete the current libpaper, instead of claiming the original libpaper package in Debian (since the ticket you've reported there hasn't moved in any way...). WDYT?

**Comment by rrthomas** [comment]
> It was packaged at least in Fedora https://src.fedoraproject.org/rpms/paper and Arch Linux https://archlinux.org/packages/extra/x86_64/paper/ , maybe others, so it would be great if an explanation was placed into README.

Thanks for that information; I hadn't realised! I have added a short note to the `README`. I'll make a new release shortly.

> Since the `paper` already is in some distros, IMHO it would be easier to get the project into Debian and obsolete the current libpaper, instead of claiming the original libpaper package in Debian (since the ticket you've reported there hasn't moved in any way...). WDYT?

The progress is not very visible, but I have a Debian Developer assisting me (I myself am a Debian Maintainer) in performing a "package salvage" operation on libpaper to update it to my version. This is preferable IMO, as without it; having two different versions of libpaper would be very confusing, not least for users.
