### ISSUE TITLE
libpaper 2 breaks libreoffice

### ISSUE THREAD

**Issue by ht990332** [rrthomas/libpaper#40]
https://cgit.freedesktop.org/libreoffice/core/tree/i18nutil/source/utility/paper.cxx#n249
Libreoffice expects the paperconf command line utility and it should just output a4, letter, etc... in lowercase according to a libreoffice developer I spoke to on IRC.

**Comment by rrthomas** [comment]
The equivalent with paper 2.x is `paper --no-size`. Paper names are case-insensitive. This doesn't seem to be a problem, since the comparison in the code you link to is case insensitive.

I apologize for the inconvenience caused by this breaking change (which is signalled by the major version bump).

Looking at the code you link to, it seems there's an opportunity for LibreOffice here, as libpaper 2 includes a comprehensive list of paper sizes (including all those mentioned in the list `aCustoms`), and works on macOS.

I'd be very happy to help the LibreOffice team integrate more of libpaper 2's functionality.

**Comment by rrthomas** [comment]
I've re-added `paperconf` in libpaper 2.1.0, but it is deprecated.
